// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDesk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707020222_FixDateTimeUtc")]
    partial class FixDateTimeUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.Property<int>("IdActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActivo"));

                    b.Property<string>("CodigoActivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoActivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int?>("IdDetalleItemOC")
                        .HasColumnType("integer");

                    b.Property<int?>("IdItemOC")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrden")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdActivo");

                    b.HasIndex("CodigoActivo")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdDetalleItemOC");

                    b.HasIndex("IdItemOC");

                    b.HasIndex("IdOrden");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("Models.AsignacionUsuario", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsignacion"));

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdParqueadero")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("integer");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdParqueadero");

                    b.HasIndex("IdUsuarioDestino");

                    b.HasIndex("IdActivo", "EstadoAsignacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Asignacion_ActivoUnico")
                        .HasFilter("\"EstadoAsignacion\" = 'Activa'");

                    b.ToTable("AsignacionesUsuario");
                });

            modelBuilder.Entity("Models.Canal", b =>
                {
                    b.Property<int>("IdCanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCanal"));

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCanal");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Canales");
                });

            modelBuilder.Entity("Models.CategoriaActivo", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasActivo");
                });

            modelBuilder.Entity("Models.DetalleItemOC", b =>
                {
                    b.Property<int>("IdDetalleItemOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleItemOC"));

                    b.Property<int?>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdItemOC")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDetalleItemOC");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdItemOC");

                    b.ToTable("DetallesItemOC");
                });

            modelBuilder.Entity("Models.DetalleSalida", b =>
                {
                    b.Property<int>("IdDetalleSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleSalida"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalida")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalleSalida");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdSalida");

                    b.ToTable("DetallesSalida");
                });

            modelBuilder.Entity("Models.HistorialActivo", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalida")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdSalida");

                    b.HasIndex("IdUsuarioEntrega");

                    b.ToTable("HistorialActivos");
                });

            modelBuilder.Entity("Models.ItemOC", b =>
                {
                    b.Property<int>("IdItemOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItemOC"));

                    b.Property<int>("CantidadEsperada")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrden")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdItemOC");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdOrden");

                    b.ToTable("ItemsOC");
                });

            modelBuilder.Entity("Models.OrdenCompra", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrden"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NumeroOC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("IdOrden");

                    b.HasIndex("NumeroOC")
                        .IsUnique();

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.Property<int>("IdParqueadero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParqueadero"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IdSede")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdParqueadero");

                    b.HasIndex("IdSede");

                    b.ToTable("Parqueaderos");
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.Property<int>("IdSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalida"));

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCanal")
                        .HasColumnType("integer");

                    b.Property<int?>("IdParqueaderoDestino")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioDestino")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroTicket")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("RegistroSalida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSalida");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("IdCanal");

                    b.HasIndex("IdParqueaderoDestino");

                    b.HasIndex("IdUsuarioDestino");

                    b.HasIndex("IdUsuarioEntrega");

                    b.ToTable("Salidas", t =>
                        {
                            t.HasCheckConstraint("CK_Salida_Destino", "\"IdUsuarioDestino\" IS NOT NULL OR \"IdParqueaderoDestino\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Models.Sedes", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSede"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSede");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdSede")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSede");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.HasOne("Models.CategoriaActivo", "Categoria")
                        .WithMany("Activos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.DetalleItemOC", "DetalleItemOC")
                        .WithMany()
                        .HasForeignKey("IdDetalleItemOC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.ItemOC", "ItemOC")
                        .WithMany("Activos")
                        .HasForeignKey("IdItemOC")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.OrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("DetalleItemOC");

                    b.Navigation("ItemOC");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("Models.AsignacionUsuario", b =>
                {
                    b.HasOne("Models.Activos", "ActivoNav")
                        .WithMany("AsignacionesUsuario")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Parqueadero", "Parqueadero")
                        .WithMany("AsignacionesUsuario")
                        .HasForeignKey("IdParqueadero")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", "Usuario")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivoNav");

                    b.Navigation("Parqueadero");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.DetalleItemOC", b =>
                {
                    b.HasOne("Models.Activos", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.ItemOC", "ItemOC")
                        .WithMany("DetallesItem")
                        .HasForeignKey("IdItemOC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("ItemOC");
                });

            modelBuilder.Entity("Models.DetalleSalida", b =>
                {
                    b.HasOne("Models.Activos", "Activo")
                        .WithMany("DetallesSalida")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Salida", "Salida")
                        .WithMany("DetallesSalida")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Models.HistorialActivo", b =>
                {
                    b.HasOne("Models.Activos", "Activo")
                        .WithMany("HistorialActivos")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Salida", "Salida")
                        .WithMany("HistorialActivos")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", "UsuarioEntrega")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEntrega")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Salida");

                    b.Navigation("UsuarioEntrega");
                });

            modelBuilder.Entity("Models.ItemOC", b =>
                {
                    b.HasOne("Models.CategoriaActivo", "Categoria")
                        .WithMany("ItemsOC")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.OrdenCompra", "OrdenCompra")
                        .WithMany("ItemsOC")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.HasOne("Models.Sedes", "Sede")
                        .WithMany("Parqueaderos")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.HasOne("Models.Canal", "CanalSolicitud")
                        .WithMany("Salidas")
                        .HasForeignKey("IdCanal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Parqueadero", "ParqueaderoDestino")
                        .WithMany("Salidas")
                        .HasForeignKey("IdParqueaderoDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Usuarios", "UsuarioDestino")
                        .WithMany("SalidasDestino")
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Usuarios", "UsuarioEntrega")
                        .WithMany("SalidasEntrega")
                        .HasForeignKey("IdUsuarioEntrega")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanalSolicitud");

                    b.Navigation("ParqueaderoDestino");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioEntrega");
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.HasOne("Models.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Sedes", "Sede")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.Navigation("AsignacionesUsuario");

                    b.Navigation("DetallesSalida");

                    b.Navigation("HistorialActivos");
                });

            modelBuilder.Entity("Models.Canal", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Models.CategoriaActivo", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("ItemsOC");
                });

            modelBuilder.Entity("Models.ItemOC", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("DetallesItem");
                });

            modelBuilder.Entity("Models.OrdenCompra", b =>
                {
                    b.Navigation("ItemsOC");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.Navigation("AsignacionesUsuario");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.Navigation("DetallesSalida");

                    b.Navigation("HistorialActivos");
                });

            modelBuilder.Entity("Models.Sedes", b =>
                {
                    b.Navigation("Parqueaderos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("SalidasDestino");

                    b.Navigation("SalidasEntrega");
                });
#pragma warning restore 612, 618
        }
    }
}
