// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDesk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819141944_AddMotivoEstadoDevolucionHistorial")]
    partial class AddMotivoEstadoDevolucionHistorial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.ActaFirma", b =>
                {
                    b.Property<int>("IdActa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActa"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentoFirmante")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdDestino")
                        .HasColumnType("integer");

                    b.Property<string>("IpFirma")
                        .HasColumnType("text");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("NombreFirmante")
                        .HasColumnType("text");

                    b.Property<string>("RutaPdf")
                        .HasColumnType("text");

                    b.Property<string>("TipoDestino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdActa");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("IdDestino", "TipoDestino");

                    b.ToTable("ActasFirma");
                });

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.Property<int>("IdActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActivo"));

                    b.Property<string>("CodigoActivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoActivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int?>("IdDetalleItemRemision")
                        .HasColumnType("integer");

                    b.Property<int?>("IdItemRemision")
                        .HasColumnType("integer");

                    b.Property<int>("IdRemision")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdActivo");

                    b.HasIndex("CodigoActivo")
                        .IsUnique();

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdDetalleItemRemision");

                    b.HasIndex("IdItemRemision");

                    b.HasIndex("IdRemision");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("Models.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdArea");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("NombreArea")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Models.AsignacionUsuario", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAsignacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoDevolucion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FormaEntregaDevolucion")
                        .HasColumnType("text");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdCanal")
                        .HasColumnType("integer");

                    b.Property<int?>("IdParqueadero")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioEntrega")
                        .HasColumnType("integer");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("NumeroTicket")
                        .HasColumnType("text");

                    b.Property<string>("ObservacionDevolucion")
                        .HasColumnType("text");

                    b.Property<string>("RegistroSalida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdCanal");

                    b.HasIndex("IdParqueadero");

                    b.HasIndex("IdUsuarioDestino");

                    b.HasIndex("IdUsuarioEntrega");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("IdActivo", "EstadoAsignacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Asignacion_ActivoUnico")
                        .HasFilter("\"EstadoAsignacion\" = 'Activa'");

                    b.ToTable("AsignacionesUsuario");
                });

            modelBuilder.Entity("Models.Canal", b =>
                {
                    b.Property<int>("IdCanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCanal"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCanal");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Canales");
                });

            modelBuilder.Entity("Models.CategoriaActivo", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCategoria");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasActivo");
                });

            modelBuilder.Entity("Models.DetalleItemRemision", b =>
                {
                    b.Property<int>("IdDetalleItemRemision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleItemRemision"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdItemRemision")
                        .HasColumnType("integer");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<bool>("Procesado")
                        .HasColumnType("boolean");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdDetalleItemRemision");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdItemRemision");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("DetallesItemRemision");
                });

            modelBuilder.Entity("Models.DetalleSalida", b =>
                {
                    b.Property<int>("IdDetalleSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleSalida"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalida")
                        .HasColumnType("integer");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.HasKey("IdDetalleSalida");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdSalida");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("DetallesSalida");
                });

            modelBuilder.Entity("Models.HistorialActivo", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("text");

                    b.Property<string>("EstadoDevolucion")
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdActivo")
                        .HasColumnType("integer");

                    b.Property<int?>("IdAsignacion")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSalida")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioEntrega")
                        .HasColumnType("integer");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdSalida");

                    b.HasIndex("IdUsuarioEntrega");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("HistorialActivos");
                });

            modelBuilder.Entity("Models.ItemRemision", b =>
                {
                    b.Property<int>("IdItemRemision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItemRemision"));

                    b.Property<int>("CantidadEsperada")
                        .HasColumnType("integer");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdRemision")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.HasKey("IdItemRemision");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdRemision");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("ItemsRemision");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.Property<int>("IdParqueadero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParqueadero"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("DA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdParqueadero");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("DA")
                        .IsUnique()
                        .HasDatabaseName("IX_Parqueaderos_DA");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Parqueaderos");
                });

            modelBuilder.Entity("Models.Remision", b =>
                {
                    b.Property<int>("IdRemision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRemision"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("NombreDocumento")
                        .HasColumnType("text");

                    b.Property<string>("NumeroRemision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaDocumento")
                        .HasColumnType("text");

                    b.HasKey("IdRemision");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.HasIndex("NumeroRemision")
                        .IsUnique();

                    b.ToTable("Remisiones");
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.Property<int>("IdSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalida"));

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("EstadoActivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("IdSalida");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdArea")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoEdicion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("CreadoPor");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdRol");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Models.ActaFirma", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.CategoriaActivo", "Categoria")
                        .WithMany("Activos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.DetalleItemRemision", "DetalleItemRemision")
                        .WithMany()
                        .HasForeignKey("IdDetalleItemRemision")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.ItemRemision", "ItemRemision")
                        .WithMany("Activos")
                        .HasForeignKey("IdItemRemision")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Remision", "Remision")
                        .WithMany()
                        .HasForeignKey("IdRemision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("DetalleItemRemision");

                    b.Navigation("ItemRemision");

                    b.Navigation("Remision");
                });

            modelBuilder.Entity("Models.Area", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.AsignacionUsuario", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Activos", "ActivoNav")
                        .WithMany("AsignacionesUsuario")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Canal", "CanalSolicitud")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdCanal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Parqueadero", "Parqueadero")
                        .WithMany("AsignacionesUsuario")
                        .HasForeignKey("IdParqueadero")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", "Usuario")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", "UsuarioEntrega")
                        .WithMany("AsignacionesEntrega")
                        .HasForeignKey("IdUsuarioEntrega")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivoNav");

                    b.Navigation("CanalSolicitud");

                    b.Navigation("Parqueadero");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioEntrega");
                });

            modelBuilder.Entity("Models.Canal", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.CategoriaActivo", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.DetalleItemRemision", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Activos", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.ItemRemision", "ItemRemision")
                        .WithMany("DetallesItem")
                        .HasForeignKey("IdItemRemision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activo");

                    b.Navigation("ItemRemision");
                });

            modelBuilder.Entity("Models.DetalleSalida", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Activos", "Activo")
                        .WithMany("DetallesSalida")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Salida", "Salida")
                        .WithMany("DetallesSalida")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activo");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Models.HistorialActivo", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Activos", "Activo")
                        .WithMany("HistorialActivos")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.AsignacionUsuario", "Asignacion")
                        .WithMany()
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Salida", "Salida")
                        .WithMany("HistorialActivos")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", "UsuarioEntrega")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEntrega")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activo");

                    b.Navigation("Asignacion");

                    b.Navigation("Salida");

                    b.Navigation("UsuarioEntrega");
                });

            modelBuilder.Entity("Models.ItemRemision", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.CategoriaActivo", "Categoria")
                        .WithMany("ItemsRemision")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Remision", "Remision")
                        .WithMany("ItemsRemision")
                        .HasForeignKey("IdRemision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Remision");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.Remision", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("ModificadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Models.Activos", b =>
                {
                    b.Navigation("AsignacionesUsuario");

                    b.Navigation("DetallesSalida");

                    b.Navigation("HistorialActivos");
                });

            modelBuilder.Entity("Models.Area", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Models.Canal", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("Models.CategoriaActivo", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("ItemsRemision");
                });

            modelBuilder.Entity("Models.ItemRemision", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("DetallesItem");
                });

            modelBuilder.Entity("Models.Parqueadero", b =>
                {
                    b.Navigation("AsignacionesUsuario");
                });

            modelBuilder.Entity("Models.Remision", b =>
                {
                    b.Navigation("ItemsRemision");
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Models.Salida", b =>
                {
                    b.Navigation("DetallesSalida");

                    b.Navigation("HistorialActivos");
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("AsignacionesEntrega");
                });
#pragma warning restore 612, 618
        }
    }
}
